<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbdatum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbdatum_model');
    } 

    /*
     * Listing of tbdata
     * 실시간 메인
     */
    function index()
    {
        $config = array();
        $config["base_url"] = base_url() . "index.php/tbdatum";
        $config["total_rows"] = $this->Tbdatum_model->get_count();
        $config["per_page"] = 300;
        $config["uri_segment"] = 2;

        $this->pagination->initialize($config);
        $page = ($this->uri->segment(2)) ? $this->uri->segment(2) : 0;
        $data["links"] = $this->pagination->create_links();

        $data['tbdata'] = $this->Tbdatum_model->get_tbdata($config["per_page"], $page);


        //$data['tbdata'] = $this->Tbdatum_model->get_all_tbdata();
        
        //$data['_view'] = 'tbdatum/index';
        $data['_view'] = 'tbdatum/realtime';

        $this->load->view('layouts/main',$data);
    }

    function realtime($mac)
    {
        $data['mac'] = $mac;
        $data['_view'] = 'tbdatum/realtime';
        $this->load->view('layouts/main',$data);
    }

    function daily($mac,$tinfo)
    {

        $data['mac'] = $mac;
        $data['tinfo'] = $tinfo;

        $data['tbdatum'] = $this->Tbdatum_model->get_tbdatum_daily_by_mac_tinfo($mac,$tinfo);

        $data['_view'] = 'tbdatum/daily';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbdatum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'mac' => $this->input->post('mac'),
				'thrhlder' => $this->input->post('thrhlder'),
				'val01' => $this->input->post('val01'),
				'tinfo' => $this->input->post('tinfo'),
            );
            
            $tbdatum_id = $this->Tbdatum_model->add_tbdatum($params);
            redirect('tbdatum/index');
        }
        else
        {            
            $data['_view'] = 'tbdatum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbdatum
     */
    function edit($idx)
    {   
        // check if the tbdatum exists before trying to edit it
        $data['tbdatum'] = $this->Tbdatum_model->get_tbdatum($idx);
        
        if(isset($data['tbdatum']['idx']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'mac' => $this->input->post('mac'),
					'thrhlder' => $this->input->post('thrhlder'),
					'val01' => $this->input->post('val01'),
					'tinfo' => $this->input->post('tinfo'),
                );

                $this->Tbdatum_model->update_tbdatum($idx,$params);            
                redirect('tbdatum/index');
            }
            else
            {
                $data['_view'] = 'tbdatum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbdatum you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbdatum
     */
    function remove($idx)
    {
        $tbdatum = $this->Tbdatum_model->get_tbdatum($idx);

        // check if the tbdatum exists before trying to delete it
        if(isset($tbdatum['idx']))
        {
            $this->Tbdatum_model->delete_tbdatum($idx);
            redirect('tbdatum/index');
        }
        else
            show_error('The tbdatum you are trying to delete does not exist.');
    }



    
    
}
