<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbdatum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    public function get_count() {
        return $this->db->count_all('tbdata');
    }

    public function get_tbdata($limit, $start) {
        $this->db->limit($limit, $start);
        $query = $this->db->get('tbdata');

        return $query->result();
    }

    /*
     * Get tbdatum by idx
     */
    function get_tbdatum($idx)
    {
        return $this->db->get_where('tbdata',array('idx'=>$idx))->row_array();
    }

    function get_tbdatum_by_mac($mac)
    {
        $this->db->order_by('idx', 'desc');
        $this->db->limit(100);
        return $this->db->get_where('tbdata',array('mac'=>$mac))->result_array();
    }

    function get_tbdatum_realtime_by_mac($mac)
    {
        $this->db->order_by('idx', 'desc');
        return $this->db->get_where('tbdata',array('mac'=>$mac))->row_array();
    }

    public function get_list_mac() {

        $this->db->select('mac');
        $this->db->distinct();
        $query = $this->db->get('tbdata');

        return $query->result();
    }

    function get_tbdatum_realtime($tinfo)
    {
        #$this->db->get_where('tbdata',array('mac'=>$mac));
        #$this->db->where('tinfo =', "2020-08-31 12:16:52");
        $this->db->order_by('mac', 'desc');
        $this->db->where('tinfo =', $tinfo);
        $query = $this->db->get('tbdata'); 

        return  $query->result_array();
    }


    function get_tbdatum_daily_by_mac_tinfo($mac,$tinfo)
    {
        #$this->db->get_where('tbdata',array('mac'=>$mac));
        #$this->db->where('tinfo =', "2020-08-31 12:16:52");
       
        $this->db->order_by('tinfo', 'asc');
        $this->db->select("tinfo");
        $this->db->select("val01");
        $this->db->select("thrhlder");
        $this->db->where('mac =', $mac);
        $this->db->where('tinfo >=',$tinfo." 00:00:00");
        $this->db->where('tinfo <=', $tinfo." 23:59:59");
        $query = $this->db->get('tbdata'); 

        return  $query->result_array();
    }

        
    /*
     * Get all tbdata
     */
    function get_all_tbdata()
    {
        $this->db->order_by('idx', 'desc');
        return $this->db->get('tbdata')->result_array();
    }
        
    /*
     * function to add new tbdatum
     */
    function add_tbdatum($params)
    {
        $this->db->insert('tbdata',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbdatum
     */
    function update_tbdatum($idx,$params)
    {
        $this->db->where('idx',$idx);
        return $this->db->update('tbdata',$params);
    }
    
    /*
     * function to delete tbdatum
     */
    function delete_tbdatum($idx)
    {
        return $this->db->delete('tbdata',array('idx'=>$idx));
    }
}
